# Formulae #
brew "awscli"
brew "fd"
brew "fzf"
brew "gnupg"
brew "lazygit"
brew "leiningen"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "zsh"

tap "homebrew/cask-fonts"

# Casks #
cask "aws-vpn-client"
cask "ccleaner"
cask "cyberduck"
cask "datagrip"
cask "firefox"
cask "font-sauce-code-pro-nerd-font"
cask "intellij-idea"
cask "iterm2"
cask "microsoft-excel"
cask "microsoft-word"
cask "obsidian"
cask "phpstorm"
cask "postman"
cask "raycast"
cask "session-manager-plugin"
cask "slack"
cask "topnotch"
